Updates image getAll to include img paths
apostrophecms/apostrophe pull request #2364
Opened 2020-09-02 20:54 UTC by abea

Fixes the media manager to get actual image paths to display images.

2020-09-02 20:57 UTC, boutell requested changes

2020-09-02 20:57 UTC, boutell commented on modules/@apostrophecms/image/index.js
> +        piece._path = await self.apos.attachment.url(piece.attachment, {
Yes we need this, but see `apostrophe-headless` for the way to do it to match our current practice for including it in RESTful responses. We use the `annotate: true` feature of `apos.attachment.all`.

```
            // Attach `_url` and `_urls` properties
            self.apos.attachment.all(pieces, { annotate: true });
```

2020-09-02 22:02 UTC, boutell approved these changes
Cool! I think we should probably do this in `getAll` by default for both pieces and pages, for parity with apostrophe-headless, but that's another ticket.

2020-09-03 19:20 UTC, stuartromanek approved these changes
lgtm

2020-09-03 19:21 UTC, merged