fixed duplicates, i18n, string substitution, replaced apply with ES2020 syntax
apostrophecms/apostrophe pull request #2371
Opened 2020-09-04 18:44 UTC by boutell

The string substitution thing doesn't even work in 2.x I think? 😆 Well, it works properly now in 3.x...

2020-09-04 18:45 UTC, boutell commented
I also dropped the `id` option because it only existed in frontend code for reasons that don't apply to our 3.x notifications technical design.

2020-09-07 13:10 UTC, falkodev approved these changes

2020-09-08 16:45 UTC, abea requested changes
Little bit. Otherwise good. Holler and I'll give a quick re-review.

2020-09-08 16:45 UTC, abea commented on modules/@apostrophecms/notification/index.js
> +const Promise = require('bluebird');
Maybe we should only bring in the `delay` method.

2020-09-08 20:33 UTC, abea approved these changes

2020-09-09 12:03 UTC, merged