The "View file" button not return the original file in the "Edit file" modal
apostrophecms/apostrophe pull request #2383
Opened 2020-09-10 16:45 UTC by qmouraret

See description here: https://gitlab-dcadcx.michelin.net/pa/apostrophe-enhancements/-/issues/1023

2020-09-10 17:56 UTC, boutell approved these changes

2020-09-11 16:38 UTC, abea approved these changes

2020-09-11 16:38 UTC, abea requested changes
Please add this to a new Changelog section. The code looks good.

2020-09-14 12:08 UTC, boutell commented
I'm going to merge and write the changelog section myself just to help move it along. Thanks Quentin.

2020-09-14 12:08 UTC, merged