Displays file size, created date, and dimensions for images
apostrophecms/apostrophe pull request #2434
Opened 2020-09-29 20:02 UTC by abea

Resolves https://apostrophecms.atlassian.net/browse/A30U-430

Displays the uploaded image size, created date (for the image piece) and dimensions in the editor view:
<img width="251" alt="Screen Shot 2020-09-29 at 3 01 48 PM" src="https://user-images.githubusercontent.com/1155984/94609685-bf09ae80-0264-11eb-99f6-b15374e914a7.png">
<img width="256" alt="Screen Shot 2020-09-29 at 3 01 53 PM" src="https://user-images.githubusercontent.com/1155984/94609688-c03adb80-0264-11eb-8ce7-a1473a2cd0e5.png">

2020-09-30 12:30 UTC, boutell approved these changes

2020-10-01 02:09 UTC, stuartromanek requested changes

2020-10-01 02:09 UTC, stuartromanek commented on modules/@apostrophecms/storybook/template/public/lib/mock-images.js
> +          wdith: dim[0],
tipo

2020-10-01 14:02 UTC, abea commented on modules/@apostrophecms/storybook/template/public/lib/mock-images.js
> +          wdith: dim[0],
balderdash

2020-10-01 18:45 UTC, stuartromanek approved these changes

2020-10-01 18:52 UTC, merged