3/multi upload
apostrophecms/apostrophe pull request #2448
Opened 2020-10-05 21:39 UTC by abea

Resolves https://apostrophecms.atlassian.net/browse/A30U-415

Adds multi-image uploading. Also breaks the uploader into its own component.

2020-10-06 12:06 UTC, boutell requested changes
Looking good, think I found a minor bug.

2020-10-06 12:06 UTC, boutell commented on modules/@apostrophecms/image/ui/apos/components/AposMediaUploader.vue
> +        await this.notifyErrors(error, 'Upload Error');
I think this method doesn't exist in the uploader component, it was left behind in the parent component.

2020-10-07 15:28 UTC, boutell approved these changes

2020-10-07 16:58 UTC, stuartromanek approved these changes
Looks good, seems to work .. the experience is a little sluggish .. the success notifications seem out of sync with when the thumbnail actually get populated (in my test all 4 image thumbs got populated at once, after all uploads were complete)

Ideally thumbnails would not wait for each other and populate the preview as they are ready

@localghost443 when you test on staging happy to help write a follow up ticket

2020-10-07 17:15 UTC, merged