Sets up quick create menu in admin menu
apostrophecms/apostrophe pull request #2503
Opened 2020-10-22 21:41 UTC by abea

Resolves https://apostrophecms.atlassian.net/browse/A30U-669, populating the quick-create menu with real piece types.

2020-10-23 00:56 UTC, boutell approved these changes

2020-10-23 16:21 UTC, abea commented
Gah, I forgot to hold the other PR for this. Merging into 3.0 instead.

2020-10-23 16:23 UTC, boutell requested changes

2020-10-23 16:23 UTC, boutell commented on modules/@apostrophecms/piece-type/index.js
> +        browserOptions.quickCreate = true;
I was thinking more like actually setting:

```
options: {
  quickCreate: true
}
```

And here where you build browserOptions, pulling that in as self.options.quickCreate.

Similarly global can shut it off cleanly via configuration.

2020-10-23 16:23 UTC, boutell commented on modules/@apostrophecms/piece-type/index.js
> +        browserOptions.quickCreate = true;
This way devs can opt out for piece types that are not so primary.

2020-10-26 15:58 UTC, boutell approved these changes

2020-10-26 16:14 UTC, merged