Avatar menu works (correct PR this time with no extraneous guff)
apostrophecms/apostrophe pull request #2518
Opened 2020-10-28 14:06 UTC by boutell

I'm choosing among the gradients Stu provided via a little math on the _id, which is fun, but of course there's no guarantee two users of interest won't happen to have the same one.

The "My Profile" and "Log Out" buttons here are hooked up now, so I removed "Log Out" from the regular admin bar.

The context menu looks a little weird here, the pointer at top kinda misses the mark, Stu maybe there's a way to adjust that?

There might be a better way to do the vertical centering of the initials here.

2020-10-28 14:18 UTC, stuartromanek requested changes

2020-10-28 15:54 UTC, stuartromanek commented
@boutell Missed your question about the tip not being on target .. we have props that can provide a vertical offset but I think we lack ones that push it horizontally .. we should equip context menus with that .

2020-10-28 20:39 UTC, boutell commented
@stuartromanek cleaned this up, am I a CSS expert now?

2020-10-29 16:17 UTC, localghost443 approved these changes
love and light. Looks good to me.

2020-10-29 16:21 UTC, merged