foreign areas now work approximately per design by Stu but could use …
apostrophecms/apostrophe pull request #2577
Opened 2020-11-17 00:06 UTC by boutell

…some CSS followup. Also, apos.area.isEmpty and similar helpers work now. Necessary casualty: apos.area cannot just be a helper that tells you to use the new {% area %} tag, so we may want to lint that another way at some point

2020-11-17 00:08 UTC, boutell commented
You can test with the `foreign-areas` branch of `a3-demo`. In that branch, the `blurb` field of articles has gone back to being an area, and it allows both image and rich text widgets to allow for seeing how both of them act.

You can also explore removing your articles page from your site in order to see that if there is no `_url` for a foreign document, it opens the settings modal for it rather than navigating there.

You might have to remove your existing `article` pieces, I'm not sure if that was actually necessary in my case but there is a warning at least because the previously existing `blurb` is not a proper area.

2020-11-18 17:24 UTC, abea requested changes

2020-11-18 17:24 UTC, abea commented on modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
> +        background-color: var(--a-warning);
Let's also make the color of the icon white to match the breadcrumbs. `var(--a-white)`

2020-11-20 21:19 UTC, boutell commented on modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue
> +    contextualWidgetDefaultData(type) {
I was fixing an unrelated bug: it gets called here and in AposAreaMenu but the implementation had been migrated to just AposAreaMenu.

2020-11-20 21:28 UTC, boutell commented
I added the confirmation and new tab logic. I wasn't quite sure what you wanted me to do with the colors, and I'm not actually sure I still even see the pencil for these; can you take a look at the visual aspects?

2020-11-23 15:21 UTC, abea requested changes

2020-11-23 15:21 UTC, abea commented on modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
> +        background-color: var(--a-warning);
This still needs the white icon. That should be done in aposWidgetControls, passing the `fill-color` prop into the icon.

2020-11-23 15:22 UTC, abea commented on modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
> +        background-color: var(--a-warning);
Though setting `color: var(--a-white)` here seems to be enough.

2020-11-23 15:23 UTC, abea commented on modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
> +        background-color: var(--a-warning);
I'm talking about this:
![Screen Shot 2020-11-23 at 9 22 48 AM](https://user-images.githubusercontent.com/1155984/99980090-76a2d480-2d6d-11eb-9a62-6d526c842467.png)

The pencil on yellow not matching the text on yellow.

2020-11-23 15:41 UTC, abea approved these changes

2020-11-23 16:00 UTC, merged