3/context menu btn
apostrophecms/apostrophe pull request #2581
Opened 2020-11-20 20:07 UTC by abea

Resolves https://apostrophecms.atlassian.net/browse/A30U-806, "Style the Undo/Redo Buttons," and finishes https://apostrophecms.atlassian.net/browse/A30U-795,  "Style the context bar"

The undo/redo icons aren't exactly the same as in the design, but they are what's included in Material icons. How do we feel about that?

2020-11-23 21:53 UTC, stuartromanek requested changes

2020-11-23 21:53 UTC, stuartromanek commented on modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue
> +          />
THese need tooltips

2020-11-23 21:53 UTC, stuartromanek commented on modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue
> +          />
Also, use the undo/redo variants

![image](https://user-images.githubusercontent.com/1889830/100018013-c2736f00-2da9-11eb-9fa4-cb9aab0e0674.png)

2020-11-23 21:56 UTC, stuartromanek requested changes
forgot one

2020-11-23 21:56 UTC, stuartromanek commented on modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue
> +          />
Also also, these buttons should use the `outline` and `no-motion` modifiers

2020-11-23 21:57 UTC, localghost443 approved these changes

2020-11-24 18:47 UTC, abea commented
We're back to think looking junky due to the autosave merge. I'm ignoring that for now since we'll need design direction for that.

2020-11-25 14:56 UTC, stuartromanek approved these changes

2020-11-25 14:59 UTC, merged