3/fix root path
apostrophecms/apostrophe pull request #2614
Opened 2020-12-03 19:27 UTC by boutell

2020-12-03 19:28 UTC, boutell commented
Migration to ensure the path property of the home page is equal to its _id, as intended for 3.x. I had an old a3-demo where this was not the case and we increasingly rely on it being true. I do not see this behavior with newly created sites. This would be one of the migrations to review later for possible removal.

2020-12-03 21:15 UTC, abea requested changes

2020-12-03 21:15 UTC, abea commented on modules/@apostrophecms/page/index.js
> +          home.path = home._id;
You don't use this reset value (nor do you need to).

2020-12-04 14:20 UTC, abea approved these changes

2020-12-04 15:55 UTC, merged