3/doc more menu
apostrophecms/apostrophe pull request #2622
Opened 2020-12-09 21:08 UTC by stuartromanek

kicks off https://apostrophecms.atlassian.net/browse/A30U-731?atlOrigin=eyJpIjoiMDM2ODNiYzE0YzE4NDNmYzgzYzE3YzU2MDYyNDNkN2MiLCJwIjoiaiJ9
- requires follow up tickets for all functionality
- Currently the new component comes ready to roll out the whole menu but maybe this should be provided by the parent context

2020-12-09 21:08 UTC, stuartromanek commented on modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarUser.vue
> -    :menu-offset="2"
unrelated menu fiddling

2020-12-09 21:09 UTC, stuartromanek commented on modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue
> +      :placement="menuPlacement"
unrelated menu fiddling

2020-12-09 21:09 UTC, stuartromanek commented on modules/@apostrophecms/ui/ui/apos/components/AposContextMenuItem.vue
> +      :class="modifiers"
new options for context menu items

2020-12-09 21:32 UTC, boutell requested changes

2020-12-09 21:32 UTC, boutell commented on modules/@apostrophecms/doc-type/ui/apos/components/AposDocMoreMenu.vue
> +          action: 'save'
This action does not exist, we are autosaving.

2020-12-09 21:32 UTC, boutell commented on modules/@apostrophecms/doc-type/ui/apos/components/AposDocMoreMenu.vue
> +          action: 'versions'
This does not exist, but we are going to have to make this list extensible by pushing it from the server via browserOptions soon (not a blocker for now).

2020-12-09 22:22 UTC, abea commented on modules/@apostrophecms/doc-type/ui/apos/components/AposDocMoreMenu.vue
> +    menuHandler(action) {
Probably will need to be an async function, but also not necessary for this story.

2020-12-09 22:24 UTC, abea reviewed
The stuff Tom said, but otherwise it looks good.

2020-12-10 14:40 UTC, boutell approved these changes

2020-12-10 14:47 UTC, merged