Webpack 5
apostrophecms/apostrophe pull request #2718
Opened 2021-02-08 22:10 UTC by boutell

Webpack 5 and its consequences.

Also: a better error message for nonexistent page type modules, correct merging of options at app.js and index.js level (like 2.x), and no reliance on setImmediate in the browser especially where polyfills might not be present.

We needed all of these (except the nice error message) for this week's priority project.

2021-02-08 22:10 UTC, boutell commented
Oh excuse me, and of course the big one, in terms of files touched: no storybook.

2021-02-08 22:12 UTC, boutell commented on modules/@apostrophecms/asset/index.js
> -function webpack(config, cb) {
No longer necessary because webpackModule's function signature is now correct to pass directly to promisify.

2021-02-08 22:12 UTC, boutell commented on modules/@apostrophecms/asset/lib/webpack.config.js
> +const merge = require('webpack-merge').merge;
New version of webpack-merge offers no "smart" method, suggests this way of requiring and using. Seems OK so far.

2021-02-08 22:12 UTC, boutell commented on modules/@apostrophecms/asset/lib/webpack.scss.js
> +                esModule: false
Required for vue-style-loader compatibility with webpack 5.

2021-02-08 22:12 UTC, boutell commented on modules/@apostrophecms/asset/lib/webpack.scss.js
> +                      'autoprefixer',
Pulls in plugins differently with webpack 5.

2021-02-08 22:41 UTC, abea requested changes
Other than that comment, it looks fine. I haven't tested it in projects with different webpack versions, so I'm trusting you've done that.

2021-02-08 22:41 UTC, abea commented on lib/moog-require.js
> +    // in app.js, that should be honored, like it was in 2.x when
We shouldn't compare to 2.x in code.

2021-02-09 13:42 UTC, boutell commented
Rewrote the comment and re-requested review.

To be clear, there is no support for multiple versions of webpack right now. Webpack 5 must be used at project level also, due to the upstream issue with vue-loader. Tickets exist to try to contribute to the resolution of that problem in the future.

2021-02-09 15:06 UTC, abea approved these changes

2021-02-10 21:23 UTC, merged