previously the auto-default to first option behavior for a required s…
apostrophecms/apostrophe pull request #2777
Opened 2021-03-02 19:35 UTC by boutell

…elect field with no def setting only took effect visually, when you hit save you would be told the field was still blank.

2021-03-02 19:36 UTC, boutell commented on modules/@apostrophecms/schema/ui/apos/components/AposInputSelect.vue
> +      next: (this.value && this.value.data != null)
Overriding similar logic in the mixin.

2021-03-02 23:01 UTC, abea requested changes
I think the issue is more that it appears that the input has a value when it does not. Even if not required, someone could look at it, see a label, and assume that value was already chosen for them as the default (or previously selected).

2021-03-04 14:22 UTC, boutell commented
The convention going back to A2 and before is that if a select element is required, the first option serves as the default value.

If we don't want that, then we need to have a design discussion about changing it. Whereas this PR fixes 3.x to behave as previous releases have.

So I would suggest that we accept this for now, as a bug fix, and that we open a ticket for a design discussion about changing the behavior if desired.

2021-03-04 14:32 UTC, abea commented
That makes sense. As long as there is no null option, this seems fine. If there is a null option (not a required field) and has no configured default, it should not show any value and default to null, which I think is what we have already.

2021-03-04 14:32 UTC, abea submitted a review, later dismissed

2021-03-04 14:34 UTC, abea submitted a review, later dismissed

2021-03-04 21:15 UTC, boutell commented
@abea I did dead code removal and purged the diff module here because it was blocking npm audit and thus the testing and the merge.

2021-03-04 22:30 UTC, abea approved these changes

2021-03-05 13:29 UTC, merged