PRO-1086 3/notification position etc
apostrophecms/apostrophe pull request #2905
Opened 2021-04-13 15:13 UTC by stuartromanek

technically part of [PRO-1086](https://linear.app/apostrophecms/issue/PRO-1086/media-library-lip) although that issue has changed over time.

This PR:
- Changes the position of notification to be from the bottom right corner to bottom center, unblocking some apostrophe UI
- Removes the initial Uploading .. notification from the media manager and puts the final upload count into the confirmation notification
- various style updates to notification UI itself

2021-04-13 21:50 UTC, abea requested changes
One code style thing. Then add to the changelog.

2021-04-13 21:50 UTC, abea commented on modules/@apostrophecms/notification/ui/apos/components/TheAposNotifications.vue
> +  .list-enter, .list-leave-to {
Split to two lines

2021-04-13 22:10 UTC, stuartromanek commented on modules/@apostrophecms/notification/ui/apos/components/AposNotification.vue
> +    background-color: var(--a-warning-fade);
`:)`

2021-04-14 13:56 UTC, abea approved these changes

2021-04-14 14:15 UTC, merged