PRO-1185 fragments calling fragments
apostrophecms/apostrophe pull request #2929
Opened 2021-04-20 00:58 UTC by boutell

Make sure fragments can:

* render other fragments declared in the same source file, like macros can
* render other fragments imported by their source file, like macros can

It took me forever to figure out these six lines of code on my own time tonight. Just couldn't let this go unfixed. Needed to know if we were going to have to pivot to twigjs or even write something new. The answer is "not today."

Nunjucks makes the proper context available in the run() function that handles the "fragment" tag itself, so I needed to return that context as part of the node so it would be available later in the run() fragment of the "render" tag.

2021-04-20 01:00 UTC, boutell commented on modules/@apostrophecms/template/lib/custom-tags/render.js
> -        // TODO this only allows a simple name, we need
This comment was out of date, you can successfully render an imported fragment.

2021-04-20 01:21 UTC, boutell commented
For verification see the home page template in this branch of a3-boilerplate:

fragments-calling-fragments

Without the PR it'll throw an error. With the PR you'll get two areas at the top of the page.

2021-04-20 14:43 UTC, abea approved these changes

2021-04-20 14:47 UTC, abea requested changes
Looks good. Please update the changelog.

2021-04-22 14:07 UTC, abea approved these changes

2021-04-22 14:15 UTC, merged