contributors can see their submissions
apostrophecms/apostrophe pull request #2935
Opened 2021-04-20 15:24 UTC by boutell

Contributors can see their submissions. Piggybacks on the PR for showing the submission count to editors/admins.

Contributors can only see their own submissions. A button to display the manage view appears in the tray area, like the palette icon. I used a custom icon component. The button appears only when you actually have submissions. No count is displayed because that sounds like an unnecessary distraction, it's just a way to get back to your own submissions.

The ability to dismiss a submission is a separate ticket already and when implemented it will be supported for contributors too as long as it was their own.

2021-04-20 15:27 UTC, boutell commented on modules/@apostrophecms/submitted-draft/index.js
> +            when(req) {
This admin bar item is to be displayed only when the other one can't be, requiring custom logic. So I added a "when" option to admin bar items, which accepts a function that makes that determination on the fly based on `req`.

2021-04-20 15:27 UTC, boutell commented on modules/@apostrophecms/submitted-draft/index.js
> +            icon: 'AposSubmittedDraftAdminBarIcon',
I wrote a component to wrap the icon in a v-if test, using the same REST API call as the fancier one for the counter.

2021-04-20 15:28 UTC, boutell commented on modules/@apostrophecms/submitted-draft/index.js
> +            'submitted.byId': req.user && req.user._id
This will only match for new submissions made after this PR, so if you have test contributors with test submissions now, you'll need to submit more.

2021-04-21 19:54 UTC, stuartromanek requested changes

2021-04-21 19:54 UTC, stuartromanek commented on modules/@apostrophecms/submitted-draft/ui/apos/components/AposSubmittedDraftAdminBarIcon.vue
> +  <arrow-expand-right-icon
This should be an `<AposIndicator />`, use the tray-full icon https://materialdesignicons.com/icon/tray-full

2021-04-21 20:30 UTC, stuartromanek commented
@boutell after a quick chat w @localghost443 we should use the icon/right-side trigger UI for all users, not just non-admin. This PR feels like the place to make that change, no?

2021-04-22 19:14 UTC, boutell commented
@stuartromanek I switched to just the one icon component for both editors and contributors as we discussed, using AposIndicator, however with a number present (editor/admin) the indicator looks funny, and without a number present it's actually not even visible although I can tell it's there.

Could you help out with the remaining frontend on this one?

2021-04-22 19:31 UTC, stuartromanek commented
@boutell i will after merge, things are already out of hand and being broken pull to pull

2021-04-23 13:46 UTC, stuartromanek approved these changes

2021-04-23 13:47 UTC, merged