dismiss submissions
apostrophecms/apostrophe pull request #2936
Opened 2021-04-21 13:45 UTC by boutell

* "Dismiss Submission" on the "more" menu for both pieces and pages
* Contributors can do it too, as long as it was their own submission
* Also refactored a little to reduce code duplication in the submit/dismiss routes
* /dismiss route is now /dismiss-submission to match the language elsewhere

2021-04-21 17:55 UTC, boutell commented
I added a separate ticket to track adding this choice in the manage view as well.

2021-04-21 19:44 UTC, stuartromanek requested changes
very cool, add the `:can-dismiss-submission` prop to `modules/@apostrophecms/ui/ui/apos/components/AposCellContextMenu.vue` as well

2021-04-22 12:44 UTC, boutell commented
I mentioned there's a separate ticket for that, but yeah let's do it here and be done will get to that today

2021-04-22 17:19 UTC, stuartromanek approved these changes

2021-04-22 17:28 UTC, merged