PRO-1202 users have no drafts
apostrophecms/apostrophe pull request #2950
Opened 2021-04-23 14:00 UTC by boutell

Hide "save draft" button, also do not show publication-related labels in manage view, same idea

2021-04-24 14:18 UTC, stuartromanek requested changes
sorry

2021-04-24 14:18 UTC, stuartromanek commented on modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManagerDisplay.vue
> +    },
extra

2021-04-26 13:43 UTC, stuartromanek approved these changes

2021-04-27 12:57 UTC, boutell commented
One more time, we're gon' review this PR
Oh yeah, alright, don't stop the review
One more time, we're gon' review this PR
Because of a merge commit

Thanks

2021-04-27 16:21 UTC, stuartromanek reviewed
see above

2021-04-27 16:21 UTC, stuartromanek commented on modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue
> +    },
Should this be part of the publishMixin? the same computed just landed in AposDocsManager

2021-04-27 16:27 UTC, stuartromanek approved these changes

2021-04-27 16:42 UTC, merged