PRO-1220 various controls available where they should not be, also related bugs caused by moduleOptions being named inconsistently
apostrophecms/apostrophe pull request #2954
Opened 2021-04-23 19:59 UTC by boutell

* "Discard Draft" and "Archive" should only be available to contributors under appropriate circumstances
* "Archive" should actually work for contributors, under appropriate circumstances
* "moduleOptions" should always be called that, if it is the computed property that retrieves options of the apostrophe module related to the component, and not an "options" prop or other beast. This was causing incompatibilities with mix-ins etc.
* As a precaution, when archiving or restoring, don't mess with `_children` unless we're dealing with a page; it could be a totally unrelated relationship of a piece

2021-04-23 21:02 UTC, abea requested changes
ESLint caught a bug. This _id isn't defined. Supposed to be `page._id`? https://github.com/apostrophecms/apostrophe/blob/3/pro-1220-discard-draft/modules/@apostrophecms/ui/ui/apos/mixins/AposPublishMixin.js#L48

2021-04-26 12:50 UTC, boutell commented on modules/@apostrophecms/admin-bar/index.js
> +        if (item.options.when) {
This has gone back out of use at the moment but I think it's a solid feature.

2021-04-26 12:52 UTC, boutell commented on modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
> +      return apos.modules[this.context.type].action;
This simpler code now works everywhere thanks to Stu's change.

2021-04-26 12:53 UTC, boutell commented on modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
> +      const result = await this.discardDraft(this.context);
This pattern covers more use cases with less code, I picked up the idea from Stu and ran with it.

2021-04-26 16:31 UTC, abea requested changes

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue
> +    headers() {
There's a confusing loop here (edit: actually less of a loop than I thought originally).

The media manager doesn't have table headers or columns. It looks like this is only used in `AposDocsManagerMixin` for `generateIcons`, but the media manager also doesn't use `icons`. Why do we need to do anything special other than return an empty array?

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue
> +          // Clone but don't omit anything, we use a lot of properties of the page
We already have klona in this component. I'd suggest using that if we're simply cloning.

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue
> +            @discardDraft="onDiscardDraft"
kebab case for the event. `discardDraft` and `dismissSubmission` below.

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManagerDisplay.vue
> +            @dismissSubmission="$emit('dismissSubmission', item._id)"
:kebab:

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/submitted-draft/ui/apos/components/AposSubmittedDraftAdminBarIcon.vue
> +  <span v-if="count > 0" class="apos-submitted-draft-admin-bar-container">
The BEM syntax should be `apos-submitted-draft-admin-bar__container`. Though I think you could shorten to `apos-submitted-drafts__container`.

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/submitted-draft/ui/apos/components/AposSubmittedDraftAdminBarIcon.vue
> +    <span v-if="canPublish" class="apos-submitted-draft-admin-bar-counter">
BEM'd to `apos-submitted-drafts__counter`

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/submitted-draft/ui/apos/components/AposSubmittedDraftAdminBarIcon.vue
> +  name: 'AposSubmittedDraftAdminBarIcon',
Shorten to `AposSubmittedDraftIcon`? The context of the admin bar doesn't seem critical.

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/submitted-draft/ui/apos/components/AposSubmittedDraftAdminBarIcon.vue
> +      // Not declared in data() because it is not reactive
🆒

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/submitted-draft/ui/apos/components/AposSubmittedDraftAdminBarIcon.vue
> +    /* TODO: hack to make it visible for now */
This shouldn't be necessary. Remove `apos-input-icon` above (I'm not sure what it's doing there) and the icon is no longer positioned absolute. Then you don't need to set the width. You'll only need to swap the order of the icon and counter, maybe.

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/ui/ui/apos/components/AposCellContextMenu.vue
> +        @dismissSubmission="$emit('dismissSubmission')"
kebab `@dismissSubmission`

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/ui/ui/apos/components/AposCellContextMenu.vue
> +    manuallyPublished(doc) {
It seems like this would be better as a computed property. Only needs to run once.

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
> +        @dismissSubmission="onDismissSubmission"
We weren't catching ourselves before, but this is now a pattern we're trying to follow. There should be an eslint warning if using an IDE.

2021-04-26 16:31 UTC, abea commented on modules/@apostrophecms/ui/ui/apos/components/AposTreeRows.vue
> +          @dismissSubmission="$emit('dismissSubmission', row._id)"
kebabs

2021-04-26 16:41 UTC, boutell commented on CHANGELOG.md
All of the main fixes concern roles that didn't exist in the previous release actually published as an alpha, so I don't think we need a major changelog item.

2021-04-26 17:03 UTC, abea commented on CHANGELOG.md
No `Add` item?

2021-04-26 17:21 UTC, boutell commented on modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
> +      return this.context.submitted && (this.canPublish || (this.context.submitted.byId === apos.login.user._id));
I disagree on this point. The entire admin UI namespace is in the context of the user, taking user actions, so we can take that as a given. Also we'd be diverging from the naming convention on the server side (`self.apos.permission.can` for example).

2021-04-26 19:08 UTC, abea approved these changes

2021-04-26 20:46 UTC, merged