Override the default redirection status code when req.statusCode is set
apostrophecms/apostrophe pull request #2963
Opened 2021-04-26 17:48 UTC by jogarijo

Currently, when redirecting a page using `req.redirect = '/somewhere'`, it is not possible to set the status code to be used for the redirection. In fact, the redirection will always use the status code 302 Found.

However, some modules like `apostrophe-personas` makes the assumption that setting `req.statusCode` will override the status code ([check index.js:302-305 on the latest commit to this day](https://github.com/apostrophecms/apostrophe-personas/blob/31c84c86bd26f42c901b4c91c2d1fd2464da8622/index.js#L302-L305)).

I found this assumption very reasonable in the idea of using ["req as a notepad of things we'd like to happen in res"](https://github.com/apostrophecms/apostrophe/blob/3360af419d73a80a7828472078da4d9b9242edfb/lib/modules/apostrophe-pages/lib/api.js#L1125-L1126), so this PR is my take on it. :slightly_smiling_face: 

Here is the updated behavior when `req.redirect` is set:
- If `req.statusCode` is set, use it for the redirection;
- If it isn't, try to use the option `statusCode` from `apostrophe-soft-redirects` ([similar to what `apostrophe-personas` does](https://github.com/apostrophecms/apostrophe-personas/blob/31c84c86bd26f42c901b4c91c2d1fd2464da8622/index.js#L304));
- Otherwise fallback to using `302` like before.

2021-04-26 17:53 UTC, jogarijo commented
When I started I was thinking to use `req.statusCode` for the redirection only when it's in the range `3xx`. But as much as it makes sense to me, some users might have really good reasons to have redirections with the status code 419. The restriction would seem arbitrary to them, so I ended up not keeping it.

2021-04-27 13:21 UTC, boutell commented
Thank you!

However it looks like the soft redirects module actually does use `req.res.redirec()` directly, so it is not involved in this situation, and you should be able to remove the extra logic for it.

2021-04-27 13:22 UTC, boutell requested changes
Thank you!

However it looks like the soft redirects module actually does use `req.res.redirect()` directly, so it is not involved in this situation, and you should be able to remove the extra logic for it.

2021-04-27 16:32 UTC, jogarijo commented
Good point, I made the change and removed the related test.

2021-04-27 16:56 UTC, boutell approved these changes
Looks good, thank you

2021-04-27 16:59 UTC, merged