3/pro 1272 contributors restoring
apostrophecms/apostrophe pull request #2994
Opened 2021-05-01 21:26 UTC by boutell

Please ensure your pull request follows these guidelines:

- [ ] Link to the related issue with requirements and/or clearly describe 1) what problem this solves and 2) the requirements to review it against.
- [ ] Update the `CHANGELOG.md` file with the added feature or fix. If there is not yet a heading for an upcoming release, add one following the established pattern.
- [ ] Keep the pull request minimal! Break large updates into separate pull requests for individual features/fixes whenever possible. Small requests get reviewed more quickly.
- [ ] All tests must pass, including the linters. Run `npm run lint` to test code linting independently.

Thanks for contributing!

2021-05-01 21:27 UTC, boutell commented on modules/@apostrophecms/ui/ui/apos/mixins/AposArchiveMixin.js
> +    async restore(doc) {
Consistency

2021-05-03 14:21 UTC, stuartromanek requested changes
Restoring content

2021-05-03 14:21 UTC, stuartromanek commented on modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
> +        this.modal.showModal = false;
restoring content use to unlock the read-only'ness of the doc editor but now your closing this window, this feels like a regression of the experience

2021-05-04 20:10 UTC, stuartromanek approved these changes

2021-05-04 20:17 UTC, merged