disable save draft where appropriate
apostrophecms/apostrophe pull request #3047
Opened 2021-05-10 18:53 UTC by boutell

2021-05-10 20:18 UTC, stuartromanek approved these changes
I made a follow up ticket for proper disabling of context menu items https://linear.app/apostrophecms/issue/PRO-1326/context-menu-items-should-be-disable-able

2021-05-14 16:17 UTC, abea commented on modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
> +      // There must be a new change since you opened the modal
I'm confused by this. I thought that was the problem.

2021-05-14 16:19 UTC, abea requested changes

2021-05-14 16:19 UTC, abea commented on modules/@apostrophecms/doc-type/ui/apos/components/AposDocMoreMenu.vue
> +    disableSaveDraft() {
Why do we need a new prop and watcher if we're already watching `isPublished` and `isModified`?

2021-05-17 16:47 UTC, boutell commented
Closing in favor of PRO-1304, if any further adjustment is needed it'll look different.

2021-05-17 16:47 UTC, closed without merging