PRO-1341 preserve the hash when updating query strings
apostrophecms/apostrophe pull request #3064
Opened 2021-05-12 17:51 UTC by boutell

Also:

* eslint fixes.
* Don't manually chop off old query strings before calling, `addQueryToUrl` is smart enough to do that.

2021-05-12 18:34 UTC, boutell commented
More importantly I guess, the existing logic failed to add the query string properly because it added it after the # and it never reached the server.

2021-05-14 15:41 UTC, abea requested changes
One changelog note. The term "hash" is part of the location API.

2021-05-14 15:41 UTC, abea commented on CHANGELOG.md
> +- In-context editing works properly when the current browser URL has a `#` part, enabling the use of the `#` part for project-specific work. Thanks to [https://stepanjakl.com/](Štěpán Jákl) for repor
I think we can call it a hash.

2021-05-14 16:11 UTC, abea requested changes
Still the changelog bit.

2021-05-17 17:02 UTC, abea approved these changes

2021-05-18 11:55 UTC, merged