3/1379 no relationship
apostrophecms/apostrophe pull request #3086
Opened 2021-05-19 19:51 UTC by abea

Makes sure there are actual relationship fields there before we show the context menu.

2021-05-19 19:52 UTC, abea commented on modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue
> +      for (const key in this.item._fields) {
I stole this like an artist.

2021-05-19 19:52 UTC, abea commented on modules/@apostrophecms/ui/ui/apos/components/AposSlatList.vue
> -      {{ message }}
There is no message.

2021-05-19 19:53 UTC, abea commented on modules/@apostrophecms/ui/ui/apos/components/AposSlatList.vue
> -    field: {
There is no field. This prop isn't used anymore, only serves to show the message, the message has been replaced in design, and the field is not passed in in any use of the thing.

2021-05-19 19:59 UTC, boutell requested changes
Hmm. I think consulting `_fields` was the original mistake here. This code would be shorter and more correct if the slat did receive the actual schema field, and could simply look at `field.schema` and check it for existence and length to determine if it is *supposed to* have a relationship. It's kind of immaterial whether it currently has populated fields or not; what matters is whether it's supposed to.

2021-05-19 20:45 UTC, abea commented
I went with passing the boolean through because the relationship input is the relevant context and we don't need to make the slats do work looking for stuff.

2021-05-20 01:00 UTC, boutell approved these changes

2021-05-20 14:10 UTC, merged