3/migrate relationship storage
apostrophecms/apostrophe pull request #3147
Opened 2021-06-04 20:35 UTC by boutell

* Reverse relationships work properly for published documents.
* Relationship subfields are now loaded properly when `reverseOf` is used.
* Relationship ids are now stored as aposDocIds (without the locale and mode part). The appropriate locale and mode are known from the request. This allows easy comparison and copying of these properties across locales and fixes a bug with reverse relationships when publishing documents. A migration has been added to take care of this conversion on first startup.
* There is test coverage.
* QA: your original a3-demo test branch, `relationship-reverset-test`, can be used for QA. I added relationship subfields. Please note: you can only edit those from the relationship input field (the autocomplete list), not from the chooser. That's a separate bug.

2021-06-04 20:35 UTC, boutell commented on modules/@apostrophecms/doc-type/index.js
> +            if (field.fieldsStorage) {
Projection for _foo should include both its ids and its field storage, and any.

2021-06-04 20:36 UTC, boutell commented on modules/@apostrophecms/schema/index.js
> +          field.fieldsStorage = forwardRelationship.fieldsStorage;
Without this reverseOf doesn't work properly with subfields.

2021-06-04 20:37 UTC, boutell commented on modules/@apostrophecms/schema/index.js
> +            field.fieldsStorage = forwardRelationship.fieldsStorage;
Less likely, but if someone chooses to find the reverse relationship via specifying idsStorage, it makes sense to infer the other bit.

2021-06-07 15:29 UTC, abea requested changes
A bit of clean up in the changelog

2021-06-07 15:29 UTC, abea commented on CHANGELOG.md
> +## UNANNOUNCED
Different from Unreleased?

2021-06-07 15:29 UTC, abea commented on CHANGELOG.md
> +## UNANNOUNCED
Is normally below `# Changelog`

2021-06-07 16:11 UTC, abea approved these changes

2021-06-07 16:43 UTC, merged