simpler value detection, allow field to be emptied after it was fille…
apostrophecms/apostrophe pull request #3208
Opened 2021-06-30 18:52 UTC by stuartromanek

Fixes two bugs in oembed fields
- Detecting existing field values was getting tripped up between `null` and `undefined`. If our content has an existing oembed value we know it will be an object so we don't have to be so careful as to what to expect
- the field's validation didn't account for filling in a field and then manually clearing it. A newly-empty oembed string field always produced an error and blocked save.

2021-06-30 18:55 UTC, stuartromanek commented
In a round-about way this is also fixing https://linear.app/apostrophecms/issue/PRO-1397/on-error-user-is-often-knocked-out-of-all-tabs-in-editor-modals

2021-07-01 12:42 UTC, boutell approved these changes

2021-07-01 13:16 UTC, abea requested changes
I found some alignment issues testing. 

<img width="474" alt="Screen Shot 2021-07-01 at 8 13 25 AM" src="https://user-images.githubusercontent.com/1155984/124130313-411d4280-da44-11eb-8f4d-0b6880ce40f3.png">

It's also not clearing that warning when the field is empty. I had a real YouTube url that I backspaced over utnil it wasn't a real thing, then empty.

I added the oembed field back to the testbed for reviewing: https://github.com/apostrophecms/testbed/pull/3

2021-07-01 13:17 UTC, abea commented
That is with the field *not* required. Same error when required as well.

2021-07-01 14:18 UTC, stuartromanek commented
@abea you're def looking at the feature branch? My experience looks like this

https://user-images.githubusercontent.com/1889830/124139079-433bcd00-da55-11eb-8f5f-3cce0818b8b0.mov

I also did a test where i (painstakingly) backspaced the entire url and got the same error clear

2021-07-01 14:31 UTC, stuartromanek commented
The alignment issue persists though, i didn't try to address that, but can

2021-07-01 14:39 UTC, stuartromanek commented
@abea fix for alignment is in

2021-07-01 16:29 UTC, abea commented
You're right. Good after a fresh install.

2021-07-01 16:29 UTC, abea approved these changes

2021-07-01 19:05 UTC, merged