PRO-1773: support for localizing tooltips, plus some new translations
apostrophecms/apostrophe pull request #3240
Opened 2021-07-15 23:37 UTC by boutell

I was going to just localize stuff before calling `v-tooltip`, but realized this did not make sense. It would be very fiddly logic to impose in each of those places.

So instead I applied the decorator pattern to `v-tooltip`, resulting in a directive that natively supports i18next.

Right now it does not have `interpolate` and `localize: false`, but these can easily be added if the use cases turn out to include them when all tooltips have been converted: call `v-tooltip` using its object syntax, in which the tooltip key is in the `content` property, and add support for `interpolate` and `localize` properties of that object in the new wrapper.

2021-07-15 23:47 UTC, boutell commented on modules/@apostrophecms/ui/ui/apos/components/AposButton.vue
> +            {{ $t(label, interpolate) }}
I also introduced interpolate support for AposButton as that is sometimes needed.

2021-07-16 13:13 UTC, abea commented on modules/@apostrophecms/ui/ui/apos/lib/vue.js
> +import LocalizedVTooltip from './localized-v-tooltip';
Let's go with `apos-v-tooltip` in case we ever want to customize anything else.

2021-07-22 19:38 UTC, abea requested changes
Please add a changelog entry.

@agilbert We should probably account for this in QA tests.

2021-07-23 12:48 UTC, boutell commented
Made those changes. It's `v-apos-tooltip` because the `v-` prefix is imposed by Vue.

2021-07-23 14:32 UTC, abea approved these changes

2021-07-23 17:13 UTC, merged