cut copy paste refinement
apostrophecms/apostrophe pull request #3276
Opened 2021-08-05 13:52 UTC by stuartromanek

2021-08-05 13:58 UTC, stuartromanek commented
@boutell not sure why it itemized all the merges from `main` .. doing this in `3/cut-copy-paste` squashed them all as one merge ..

2021-08-05 15:34 UTC, boutell requested changes

2021-08-05 15:34 UTC, boutell commented on modules/@apostrophecms/area/ui/apos/components/AposAreaMenu.vue
> +          :key="(item.type + '_' || '') + item.label"
I don't think this can ever be falsy due to the `+` with `_`, so I don't see how the empty string case would ever happen?

2021-08-06 14:33 UTC, boutell approved these changes

2021-08-06 15:06 UTC, merged