Pro 1834 wizard confirm
apostrophecms/apostrophe pull request #3291
Opened 2021-08-10 21:26 UTC by gregvanbrug

Resolves:
- https://linear.app/apostrophecms/issue/PRO-1834/as-an-editor-confirming-localization-settings-on-a-document-i-can-see

Includes UI, tooltips, and updated form validation. Form submission integration needs to be done.

2021-08-10 23:03 UTC, boutell requested changes

2021-08-10 23:03 UTC, boutell commented on modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
> +      tooltips: {
I believe these support i18n keys.

2021-08-11 13:36 UTC, gregvanbrug commented on modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
> +                  :value="wizard.values.relatedDocumentTypesToLocalize"
Yep, you're right. Removed.

2021-08-11 13:36 UTC, gregvanbrug commented on modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
> +      tooltips: {
Added.

2021-08-11 15:41 UTC, boutell approved these changes

2021-08-11 15:56 UTC, merged