busy screen
apostrophecms/apostrophe pull request #3293
Opened 2021-08-11 15:58 UTC by gregvanbrug

Resolves:
- https://linear.app/apostrophecms/issue/PRO-1849

Busy state UI using current components. New ticket added for updating the spinner to the new visual.

2021-08-11 18:43 UTC, gregvanbrug commented
Moved the busy state into `AposModal` with the ability to trigger the screen with a `busy` property and the ability to update the text with a `busyTitle` property in the `modal` object.

2021-08-12 18:09 UTC, boutell requested changes
The last step here is to integrate it with `TheAposBusy` and `TheAposModals` so that the standard busy mechanism, which you get "for free" with no bookkeeping just by passing the `busy: true` option to an `apos.http.*` call and awaiting it, recognizes when the topmost modal offers a `busyTitle` and engages that rather than the standard global busy display. Then `submit` will not have to set and clear the `busy` property. It'll just work.

2021-08-13 13:57 UTC, boutell approved these changes

2021-08-16 20:43 UTC, boutell commented
@gregvanbrug planning to merge?

2021-08-16 21:06 UTC, merged