PRO-1889 (b): fix determination of hostname change
apostrophecms/apostrophe pull request #3328
Opened 2021-08-23 18:02 UTC by boutell

2021-08-23 18:03 UTC, boutell commented
With this change switching between locales with different hostnames transfers the session again.

2021-08-23 19:16 UTC, abea requested changes
Looks fine, but it's failing two tests.

2021-08-24 19:28 UTC, boutell commented
@abea I addressed the failing tests in a separate ticket (PR now assigned to you for review).

2021-08-24 20:55 UTC, abea approved these changes

2021-08-24 20:55 UTC, merged