PRO-2001 fix and test previous and next filters (bumm, bumm, BUMMM, BWAH-NAAA)
apostrophecms/apostrophe pull request #3365
Opened 2021-08-30 11:27 UTC by boutell

Fixes #3364

This is a draft because we have a release today that this isn't QA'd for. Will add release notes before making it a final PR.

"Previous" and "next" have funny semantics when the default sort order happens to be negative, i.e. reverse chronological by updatedAt, and this could also be an issue for a blog post, but in that situation it would be up to the frontend developer to decide what to actually label these on the front end. From the back end's standpoint "previous" and "next" take you to the previous or next thing according to the sort order in effect, whatever that is. "Next" means "one step further down the list."

2021-08-31 14:33 UTC, abea requested changes
Changelog please. Then is good.

2021-09-02 14:56 UTC, abea requested changes
it looks like this is going to run into merge issues in the changelog since it was created before two releases that have gone out. Could you merge main into this to clear that up first?

2021-09-02 15:05 UTC, boutell commented
done

2021-09-02 15:05 UTC, abea approved these changes

2021-09-02 17:35 UTC, merged