Hotfix for possible SVG spearsphishing attack vector
apostrophecms/apostrophe pull request #3394
Opened 2021-09-07 20:19 UTC by boutell

This is low probability, but possible. This initial PR is against a base branch that matches 3.3.1. I like this procedure better than starting out with a PR against main, because this way no error-prone cherry-picking is required, just a merge to main after release.

2021-09-07 20:20 UTC, boutell commented on modules/@apostrophecms/attachment/index.js
> +            ...(criteria || {}),
A bug that got in the way: the `each` method for attachment migrations was ignoring its `criteria` argument.

2021-09-07 20:35 UTC, abea requested changes
Also an eslint error

2021-09-07 20:35 UTC, abea commented on modules/@apostrophecms/attachment/index.js
> +            await self.sanitizeSvg(file, info);
The `info` parameter isn't used in the method.

2021-09-08 14:17 UTC, abea submitted a review, later dismissed

2021-09-08 14:24 UTC, abea approved these changes

2021-09-08 14:25 UTC, merged