localized media info, fixed file size display
apostrophecms/apostrophe pull request #3396
Opened 2021-09-08 12:42 UTC by boutell

2021-09-09 16:12 UTC, abea requested changes

2021-09-09 16:12 UTC, abea commented on modules/@apostrophecms/i18n/i18n/en.json
> +  "mediaDimensions": "Dimensions: {{ width }} x {{ height }}",
This is a different `𝗑` than the original one. I think the one originally used is more associated with multiplication rather than being a letter.

2021-09-09 16:12 UTC, abea commented on modules/@apostrophecms/i18n/i18n/en.json
> +  "mediaCreatedDateDayjsFormat": "MMM Do, YYYY",
There is an established pattern for localized dayjs formats. Should be something like `dayjsMediaCreatedFormat`

2021-09-09 16:12 UTC, abea commented
This should maybe hold for the next release at this point.

2021-09-09 17:03 UTC, boutell commented
OK we'll hold.

2021-09-13 12:46 UTC, boutell commented
Ready for review, a draft until today's release goes out so it doesn't accidentally sneak in without QA.

2021-09-13 14:30 UTC, abea submitted a review, later dismissed

2021-09-13 20:41 UTC, abea approved these changes

2021-09-13 20:48 UTC, merged