PRO-2353 support for overriding Vue components at project level
apostrophecms/apostrophe pull request #3557
Opened 2021-11-24 14:39 UTC by boutell

2021-11-24 14:42 UTC, boutell commented
See the `custom-logo-vue-component` of our testbed project for a demo in which the apostrophe logo in the admin bar (not the one seen when logged out) is overridden.

2021-11-24 16:23 UTC, abea requested changes
It works beautifully. We will need separate documentation and should keep the changelog to the change.

2021-11-24 16:23 UTC, abea commented on CHANGELOG.md
> +* Developers can now override any Vue component of the ApostropheCMS admin UI by providing a component of the same name in the `ui/apos/components` folder of their own module. Apostrophe will use the
Let's try to keep it to a changelog. We should definitely have a docs update with this as well.

2021-11-29 16:29 UTC, boutell commented
Dialed it way back but left a little hint that there are other ways.

2021-11-29 17:09 UTC, abea approved these changes

2021-11-29 18:02 UTC, merged