Fixes the server-side and template l10n debugging plugin
apostrophecms/apostrophe pull request #3571
Opened 2021-12-01 21:53 UTC by abea

During documentation I noticed the server-side and template l10n strings were not debugged the same as UI strings. The plugin needed to be activated in the init method.

+++++++++++++++

Please ensure your pull request follows these guidelines:

- [x] Link to the related issue with requirements and/or clearly describe 1) what problem this solves and 2) the requirements to review it against.
- [x] Update the `CHANGELOG.md` file with the added feature or fix. If there is not yet a heading for an upcoming release, add one following the established pattern.
- [x] Keep the pull request minimal! Break large updates into separate pull requests for individual features/fixes whenever possible. Small requests get reviewed more quickly.
- [x] All tests must pass, including the linters. Run `npm run lint` to test code linting independently.

Thanks for contributing!

2021-12-01 21:53 UTC, abea commented on modules/@apostrophecms/i18n/index.js
> +    if (value === l10nKey) {
This is copied from the i18next.js file

2021-12-02 13:55 UTC, boutell requested changes

2021-12-02 13:55 UTC, boutell commented on modules/@apostrophecms/i18n/index.js
> +      postProcess: 'apostrophei18nDebugPlugin'
Do you have a second to fix the capitalization to be consistent (the I should be capitalized in all versions of the name apostropheI18nDebugPlugin)? I know it's not a new problem but we're perpetuating it.

2021-12-02 20:32 UTC, boutell approved these changes

2021-12-02 21:58 UTC, merged