PRO-2687 default relationship editor and fields
apostrophecms/apostrophe pull request #3718
Opened 2022-04-19 19:26 UTC by boutell

## Summary

* Piece type modules may specify a default set of fields for any relationship with that type, as well as a vue component to be used to edit those fields.
* Configured that for the `@apostrophecms/image` type and removed it from the `@apostrophecms/image-widget` type, showing that custom slideshow widgets etc. will "just work" with cropping without having to think about this.

## What are the specific steps to test this change?

*For example:*

Crop an image for a particular placement in an image widget in the testbed, as per normal. Note that this works and displays the proper editor even though the configuration for that exists only in the image piece type.

## What kind of change does this PR introduce?

- [ ] Bug fix
- [X] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [X] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2022-04-19 19:26 UTC, boutell commented on CHANGELOG.md
> +* Images may now be cropped to suit a particular placement after selecting them.
Added missing changelog for this work in general.

2022-04-19 19:26 UTC, boutell commented on modules/@apostrophecms/schema/index.js
> -            fail('withType property is missing. Hint: it must match the "name" property of a doc type. Or omit it and give your relationship the same name as the other type, with a leading _ and opti
Unrelated fix, we don't use "name" anymore.

2022-04-21 08:34 UTC, ValJed requested changes

2022-04-21 08:34 UTC, ValJed commented on modules/@apostrophecms/schema/index.js
> +            const withTypeManager = self.apos.doc.getManager(field.withType);
This line (1031) can be removed.

2022-04-21 08:34 UTC, ValJed commented on modules/@apostrophecms/schema/index.js
> +            const fields = withTypeManager.options.relationshipFields && withTypeManager.options.relationshipFields.add;
Could indent some lines here.

2022-04-25 12:36 UTC, merged