Pro 2839 redirect query
apostrophecms/apostrophe pull request #3775
Opened 2022-05-30 15:38 UTC by ETLaurent

## Summary

*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2022-05-30 16:39 UTC, ETLaurent commented on lib/modules/apostrophe-soft-redirects/index.js
> +          if (self.local(doc._url) !== req.path) {
ℹ️ use `req.path` which doesn't contain the query params

2022-05-30 16:39 UTC, ETLaurent commented on lib/modules/apostrophe-soft-redirects/index.js
> +            return req.res.redirect(statusCode, `${self.local(doc._url)}${queryParams}`);
ℹ️ add the query params to the url, if any

2022-06-07 15:24 UTC, boutell requested changes

2022-06-07 15:24 UTC, boutell commented on lib/modules/apostrophe-soft-redirects/index.js
> +    self.buildQueryString = function(parameters) {
This method will fail on nested data structures and doesn't escape the keys and values. Use `qs.stringify`

2022-06-09 20:14 UTC, boutell approved these changes

2022-06-10 14:18 UTC, merged