Fix max login attempts msg
apostrophecms/apostrophe pull request #3776
Opened 2022-05-31 15:06 UTC by ValJed

[1142](https://gitlab-dcadcx.michelin.net/pa/apostrophe-enhancements/-/issues/1142)

## Summary
Fixes missing plural label for login max attempts error message.
For normal login and requirement verification

## What are the specific steps to test this change?

* Link branch to A3 project
* Setup `lockoutMinutes` in login module config
```javascript
    '@apostrophecms/login': {
      options: {
        throttle: {
          lockoutMinutes: 2
        }
      }
    },
```
* Try to exceed max login attempt in initial login, the message should take into account the lockoutMinutes value
* Try to exceed max login attempt in totp login, the message should take into account the lockoutMinutes value

## What kind of change does this PR introduce?

- [X] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [X] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

2022-05-31 18:38 UTC, boutell commented on CHANGELOG.md
> +## unreleased
UNRELEASED

2022-05-31 18:44 UTC, boutell requested changes

2022-05-31 18:44 UTC, boutell commented on CHANGELOG.md
> +## unreleased
UNRELEASED

2022-05-31 18:44 UTC, boutell commented on CHANGELOG.md
> +### Fixes for
Just "Fixes"

2022-06-01 14:38 UTC, ValJed commented on modules/@apostrophecms/login/index.js
> +              ? 'apostrophe:loginMaxAttemptsReached_plural'
Right, it's working well I just forgot the plural was handled automatically.

2022-06-01 20:16 UTC, boutell approved these changes

2022-06-03 12:57 UTC, merged