handle private locales
apostrophecms/apostrophe pull request #3822
Opened 2022-06-27 15:23 UTC by ETLaurent

## Summary

If a locale has a `private: true` option, accessing to the content in that locale while logged out will result in a 404.

## What are the specific steps to test this change?

Link `apostrophe` into a project.
In the project, configure `@apostrophecms/i18n` module with one or several locales with the `private: true` option:

![image](https://user-images.githubusercontent.com/8301962/175975897-99539447-fc21-444c-8643-b1414db05f48.png)

While logged in, you should be able to access to the private locales, but not logged out.

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [ ] Related documentation has been updated
- [x] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2022-06-27 15:30 UTC, ETLaurent commented on CHANGELOG.md
> +* Handle `private: true` locale option in i18n module, preventing logged out users from accessing the content of a private locale.
"from accessing _to_ the content"?

2022-06-28 14:46 UTC, boutell commented on CHANGELOG.md
> +* Handle `private: true` locale option in i18n module, preventing logged out users from accessing the content of a private locale.
This language is good.

2022-06-28 14:58 UTC, boutell requested changes

2022-06-28 15:52 UTC, ETLaurent commented on modules/@apostrophecms/i18n/index.js
> +            .reduce((memo, [ name, options ]) => ({
Hmm, I find that using a `reduce` is clearer to re-construct the object here, but I can change it

2022-06-28 16:10 UTC, ETLaurent commented on modules/@apostrophecms/i18n/index.js
> +            .reduce((memo, [ name, options ]) => ({
Actually, no need for a `map`, so indeed that's better 👍

2022-06-29 14:28 UTC, boutell approved these changes

2022-07-04 09:46 UTC, ETLaurent commented
Merging: previously approved, only a changelog conflict has been resolved

2022-07-04 09:46 UTC, merged