display placeholder for video-widget
apostrophecms/apostrophe pull request #3885
Opened 2022-09-20 10:51 UTC by ETLaurent

## Summary

*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2022-09-21 13:11 UTC, ETLaurent commented
🧪 Unit tests will be added after #3886 is merged.

2022-09-21 13:20 UTC, boutell requested changes

2022-09-21 13:20 UTC, boutell commented on modules/@apostrophecms/video-widget/views/widget.html
> +    width="100%"
Same concern. Use a class, provide default styles that can be overridden.

2022-09-23 16:37 UTC, ETLaurent commented on modules/@apostrophecms/video-widget/index.js
> +    placeholderUrl: 'https://youtu.be/ukR7bD90Y0g'
```suggestion
    placeholderUrl: 'https://youtu.be/Q5UX9yexEyM'
```

2022-09-29 10:55 UTC, merged