fix mout vulnerability by replacing credential package with credentials
apostrophecms/apostrophe pull request #3966
Opened 2022-12-14 16:54 UTC by ETLaurent

## Summary

* Replace [`credential`](https://www.npmjs.com/package/credential) package with [`credentials`](https://www.npmjs.com/package/credentials) to fix the [`mout` Prototype Pollution vulnerability](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7792).

## What are the specific steps to test this change?

- link apostrophe into a project (testbed for instance)
- test login with a correct password -> should log in
- test login with a wrong password -> should not log in

⚠️ former users that were created before this code change (i.e with the credential package) should still be able to log in with their password.

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [x] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2022-12-15 16:22 UTC, ETLaurent commented on test/users.js
> +      '{"hash":"/1GntJjtkMY1iPmQY1gn9f3bOZ5tb2qFL+x4qsDerZq2JL8+12TERR4/xqh246wBb+QJwwIRsF/6E+eccshsLxT/","salt":"GJHukLNaG6xDgdIpxVOpqV7xQLQM7e5xnhDW7oaUOe7mTicr7Ca76M4uUJalN/cQ68CE9O7yXZ5WJOz4RN/ud
Editing userSafe with a passwordHash generated with the old `credential` package

2022-12-15 16:22 UTC, ETLaurent commented on test/users.js
> +    await apos.user.safe.remove({ username: 'olduser' });
remove userSafe for scoping

2022-12-15 20:01 UTC, boutell requested changes
💯 just make clear in the changelog that there was never an actual vulnerability

2022-12-16 15:32 UTC, ETLaurent commented on CHANGELOG.md
> +* Replace [`credential`](https://www.npmjs.com/package/credential) package with [`credentials`](https://www.npmjs.com/package/credentials) to fix the [`mout` Prototype Pollution vulnerability](https:
Used your phrase as it is very clear

2022-12-16 15:50 UTC, boutell approved these changes

2022-12-16 16:02 UTC, merged