PRO-3409 named anchors
apostrophecms/apostrophe pull request #3967
Opened 2022-12-15 22:51 UTC by boutell

## Summary

Implemented named anchor editing. Named anchors are implemented as spans with an `id` attribute, because in our tiptap-based editor everything with editable attributes has to be eventually wrapped as a tag. Existing `<a name>` tags are migrated. If they have no children, the new span is automatically modified to wrap the next text node, so that there is something for our editor to recognize. Otherwise the span gets discarded by tiptap.

In an extreme edge case where there is no next text node in traversal of the whole document an anchor emoji is inserted but this shouldn't happen.

## What are the specific steps to test this change?

Include `anchor` on the toolbar. Mark some text that is a few screens down the page as a named anchor, then make a link to it somewhere else using `#anchorname`. That link should work after you publish and load the page in an incognito window. Or in preview mode, probably.

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [X] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [X] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

<img width="508" alt="Screenshot 2022-12-15 at 5 44 36 PM" src="https://user-images.githubusercontent.com/32125/207983749-3ecd35c7-5e22-4841-b928-5277cc137f18.png">
<img width="590" alt="Screenshot 2022-12-15 at 5 44 40 PM" src="https://user-images.githubusercontent.com/32125/207983750-f555a30a-980d-4d59-a2e5-5040b1371d58.png">

2022-12-15 22:52 UTC, boutell commented on modules/@apostrophecms/rich-text-widget/index.js
> +        output.permalinkIds = (anchors && anchors.map(anchor => {
Unrelated fix for the permalinks PR, which this will merge into.

2022-12-16 12:41 UTC, ETLaurent commented on modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
> +        if (((typeof name) === 'string') && name.length) {
could early `continue`  to reduce indentation

2022-12-16 13:35 UTC, ETLaurent requested changes
Tested on testbed, works well!

Could `AposTiptapLink.vue` and `AposTiptapAnchor.vue` share their common code in a mixin? 
Or is it urgent? (and could be done in another time)

2022-12-16 13:35 UTC, ETLaurent commented on modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
> +            anchor.prepend(span);
could we [replace](https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith) the old anchor instead of appending the new one in it?

2022-12-16 13:35 UTC, ETLaurent commented on modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapAnchor.vue
> +            label="apostrophe:removeAnchor"
missing translation

<img width="411" alt="image" src="https://user-images.githubusercontent.com/8301962/208108183-e2f47d37-26ee-4f90-bdcb-3aec7c78e48c.png">

2022-12-16 13:35 UTC, ETLaurent commented on modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapAnchor.vue
> +        <footer class="apos-link-control__footer">
```suggestion
        <footer class="apos-anchor-control__footer">
```

2022-12-16 13:35 UTC, ETLaurent commented on modules/@apostrophecms/rich-text-widget/ui/apos/tiptap-extensions/Anchor.js
> +};
new line

2022-12-16 14:40 UTC, ETLaurent requested changes
just the missing translation and [this comment](https://github.com/apostrophecms/apostrophe/pull/3967/files#r1050761464), and it's good to me!

<img width="374" alt="image" src="https://user-images.githubusercontent.com/8301962/208122314-1bcd3c9f-da0a-4794-a073-56d5044389c2.png">

2022-12-16 14:42 UTC, ETLaurent reviewed
2 missing keys actually

<img width="416" alt="image" src="https://user-images.githubusercontent.com/8301962/208122784-6e62caf9-0a49-4f77-a006-7c45557bf8b7.png">

2022-12-16 14:46 UTC, ETLaurent requested changes

2022-12-16 14:46 UTC, ETLaurent commented on modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapAnchor.vue
> +          label: 'Anchor Name',
should be a i18n key, what do you think?

2022-12-16 15:11 UTC, ETLaurent approved these changes

2022-12-16 15:13 UTC, merged