updagres passport version
apostrophecms/apostrophe pull request #4059
Opened 2023-02-20 17:57 UTC by ValJed

[PRO-3654](https://linear.app/apostrophecms/issue/PRO-3654/[a2]-passport-package-vulnerability)

## Summary

Upgrades passport to 0.6 due to security vulnerabilities.

## What are the specific steps to test this change?

I tested, the login system that uses passport methods:
* initialize
* session
* use
* authenticate
* serializeUser
* deserializeUser

Is still working on version 0.6. The TOTP module has been successfully tested also.
I noticed that `apostrophe-passport` also interacts with passport instance through `self.apos.login.passport`.
Since it uses the same methods than the core and nothing more (authenticate, use), it should work as well (and we can't test every possible passport module).

A warning has been added in the changelog since I didn't test every passport method. Some projects may interact with the passport instance by accessing `self.apos.login.passport`. In this case they should check themselves if everything is still working.

## What kind of change does this PR introduce?

- [X] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [X] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

2023-02-21 16:58 UTC, boutell requested changes

2023-02-21 16:58 UTC, boutell commented on CHANGELOG.md
> +* Upgrades passport to the latest version in order to fix security vulnerability. For passport methods that are internally used by Apostrophe everything is still working. For projects that are access
Let's put this under a "Security" heading, not just "Fixes".

However, let's also reword it:

"... latest version in order to ensure session regeneration when logging in or out. This adds additional security to logins by mitigating any risks due to XSS attacks. Apostrophe is already robust against XSS attacks."

I don't think there is a plausible scenario to exploit the issue on a typical Apostrophe site, but more security is good.

2023-02-22 10:32 UTC, ValJed commented on CHANGELOG.md
> +* Upgrades passport to the latest version in order to fix security vulnerability. For passport methods that are internally used by Apostrophe everything is still working. For projects that are access
👍🏼

2023-02-22 14:13 UTC, boutell approved these changes

2023-02-22 14:34 UTC, merged