added date verification for null date and no default value
apostrophecms/apostrophe pull request #4297
Opened 2023-09-24 18:13 UTC by AllanKoder

## Summary

*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*

Issue number #4291. Empty dates for piece types are no longer filled with the current date after submitting nothing. 
## What are the specific steps to test this change?

1. create a default apos app. 
2. create a piece type: 
```module.exports = {
  extend: '@apostrophecms/piece-type',
  options: {
    label: 'Testing Piece',
  },
  fields: {
    add: {
      date: {
        label: 'Date?',
        type: 'date'
      },
    },
    group: {
      basics: {
        label: 'Basics',
        fields: [ 'date']
      }
    }
  },
  columns: {
    add: {
      date: { label: 'Confirmed On', component: 'AposCellDate' }
    }
  }
};
```
3. create the new piece type and set date as empty
4. the date should remain as an empty string

## What kind of change does this PR introduce?
*(Check at least one)*

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2023-09-25 21:26 UTC, AllanKoder commented
> Thanks for contributing!
> 
> However, I think this should be handled in the component on the front end. There's nothing wrong with `null` as a representation of "no value," and handling it on the front end will avoid the need for a data migration for existing data.
> 
> Can you take a look at handling it that way?

Hi, I edited the backend code and added a null filter for AposCellDate. However, I could not remove the backend code completely as one of the issues was that a front end user could submit an empty date and the `convert` function in addFieldTypes.js would turn the null value into a date with the line `self.apos.launder.date(newDateVal, field.def);` and the data would be saved in the mongo docs and rendered onto the frontend. Hence, I think the only way to allow empty dates is to set the value as a null.

Let me know if my line of thinking is broken somewhere. Thanks so much!

2023-09-26 14:23 UTC, boutell requested changes

2023-09-26 14:23 UTC, boutell commented on modules/@apostrophecms/schema/lib/addFieldTypes.js
> +        destination[field.name] = null
👍 I'm OK with this. Technically it's a change of behavior, but I do not think this behavior served anyone on the server side, where it was very unexpected. Please add a space after `field.def)` and before the `{`

2023-09-26 14:23 UTC, boutell commented on modules/@apostrophecms/schema/lib/addFieldTypes.js
> +        destination[field.name] = null
Also make sure the unit tests still pass (`npm test`) if not we might need to adjust one to account for not automatically filling in today's date.

2023-09-26 14:23 UTC, boutell commented on modules/@apostrophecms/ui/ui/apos/components/AposCellDate.vue
> +      return value ? this.formatDateColumn(value) : "";
Looks good.

2023-09-26 15:39 UTC, boutell approved these changes
Thank you!

2023-09-26 16:05 UTC, merged