Pro 4966 condition met required
apostrophecms/apostrophe pull request #4322
Opened 2023-10-23 08:13 UTC by ValJed

[PRO-4966](https://linear.app/apostrophecms/issue/PRO-4966/replicate-condition-met-property-as-condition-met-required-property)

## Summary

* `condition-met-required` has been added.
* Works for all types of fields.

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2023-10-25 08:55 UTC, ValJed commented on modules/@apostrophecms/schema/ui/apos/components/AposInputRadio.vue
> +            :is="`${next === value ? 'check-bold-icon' : 'span'}`"
Makes no sense since there is a v-if but whetever not the purpose of the PR.

2023-10-27 15:42 UTC, falkodev requested changes
Also, with A3 core, cypress tests are ok:
<img width="1788" alt="image" src="https://github.com/apostrophecms/apostrophe/assets/11479686/1ca8b217-c261-4514-89dd-7612e32c7ddc">

With your branch, like half of them fail for `fields` test:
<img width="899" alt="image" src="https://github.com/apostrophecms/apostrophe/assets/11479686/95161ba3-759d-4f71-8aa9-6fab78cb8c97">

2023-10-27 15:42 UTC, falkodev commented on modules/@apostrophecms/schema/index.js
> +        if (field.if && field.if.$or && !Array.isArray(field.if.$or)) {
already present on line 1246

2023-10-28 10:48 UTC, myovchev reviewed
It looks to me like a major performance improvement. Few recommendations/concerns:
- `AposDocEditor` might need its own `logic` mixin, as it's sometimes used in projects to deliver custom functionality (I have a project in mind). It think this is a good time for that.
- The computed prop optimization comes with a risk of "stale" (non-reactive) data in some edge cases. I would think of combination of dynamic `choices` and related condition - we would need testbed case testing those (if we don't have currently)

2023-10-29 13:04 UTC, ValJed commented
@falkodev this is a tests problem. I fixes the fact that the tab `Templates` wasn't loaded at start so the tab `strings` was triggered. Fixed with this change: https://github.com/apostrophecms/testbed/pull/206/files
Fields tests are passing with it.

2023-10-30 12:16 UTC, boutell approved these changes

2023-10-31 08:31 UTC, ValJed commented on modules/@apostrophecms/schema/ui/apos/components/AposInputRadio.vue
> +            :is="`${next === value ? 'check-bold-icon' : 'span'}`"
The if isn't new I just aligned props.

2023-10-31 08:35 UTC, ValJed commented on modules/@apostrophecms/schema/index.js
> +        if (field.if && field.if.$or && !Array.isArray(field.if.$or)) {
Removed

2023-10-31 14:30 UTC, merged