Feature/conditionally required fields
apostrophecms/apostrophe pull request #4328
Opened 2023-10-31 17:33 UTC by ValJed

## Summary

*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2023-11-02 12:48 UTC, boutell submitted a review, later dismissed

2023-11-02 12:48 UTC, boutell commented on modules/@apostrophecms/schema/ui/apos/mixins/AposInputFollowingMixin.js
> +      for (const field of this.schema) {
Have we confirmed this mixin is only used in contexts where the schema computed property exists?

2023-11-02 12:48 UTC, boutell commented on modules/@apostrophecms/schema/ui/apos/mixins/AposInputFollowingMixin.js
> +      for (const field of this.schema) {
... I confirmed that. Looks good.

2023-11-03 14:29 UTC, haroun requested changes

2023-11-03 14:29 UTC, haroun commented on modules/@apostrophecms/schema/index.js
> +            if (destinationKey < val.min) {
we should flatten this `if`

2023-11-03 14:31 UTC, falkodev commented on modules/@apostrophecms/schema/ui/apos/lib/conditionalFields.js
> +        return fieldValue >= val.min;
Done

2023-11-03 14:32 UTC, falkodev commented on modules/@apostrophecms/schema/index.js
> +            if (destinationKey < val.min) {
Done

2023-11-03 14:49 UTC, haroun approved these changes

2023-11-03 14:49 UTC, merged