Pro 4962 min max if condition
apostrophecms/apostrophe pull request #4329
Opened 2023-10-31 17:42 UTC by falkodev

https://linear.app/apostrophecms/issue/PRO-4962/as-a-developer-i-want-to-be-able-to-make-a-required-field-optional

Extracted `evaluate` from `isVisible` into `evaluateCondition`.
Works for both `if` and `requiredIf`
Tests updated
Run `npx mocha --watch --watch-files test/schemas.js,modules/@apostrophecms/schema/index.js test/schemas.js`

2023-10-31 18:30 UTC, boutell requested changes
Please resolve conflicts

2023-11-01 13:07 UTC, boutell approved these changes

2023-11-01 13:31 UTC, ValJed approved these changes

2023-11-01 13:32 UTC, ValJed commented
Looks good, for now `$ne` as well as min and max are not supported in frontend. you might create a ticket for that since you added the backend part already.

2023-11-01 13:50 UTC, merged