Pro 4998 recaptcha token on submit
apostrophecms/apostrophe pull request #4336
Opened 2023-11-10 09:06 UTC by haroun

## Summary

Add support for `uponSubmit` requirements in login phases

## What are the specific steps to test this change?

Each steps below requires on valid login attempt upon page load and one invalid then valid login attempt to validate that we can recover the login process after a failed attempt.

1. Try to login without any login requirements
2. Try to login with login-recaptcha enabled
3. Try to login with login-totp enabled
4. Try to login with login-hcaptcha enabled
5. Try to login with both login-recaptcha and login-totp enabled

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2023-11-10 16:41 UTC, boutell requested changes

2023-11-10 16:41 UTC, boutell commented on CHANGELOG.md
> +* Add the possibility to add custom classes to notifications.
Isn't this part of another PR?

2023-12-12 16:05 UTC, haroun commented on CHANGELOG.md
> +* Add the possibility to add custom classes to notifications.
I've updated the target PR

2023-12-13 20:34 UTC, boutell requested changes

2023-12-13 20:34 UTC, boutell commented on modules/@apostrophecms/login/index.js
> +          for (const [ name, requirement ] of Object.entries(onTimeRequirements)) {
Refactor to a method and call it twice, since the code is exactly the same.

2024-02-01 13:41 UTC, boutell approved these changes

2024-02-05 12:45 UTC, merged