Pro 5297 cache fix
apostrophecms/apostrophe pull request #4373
Opened 2023-12-19 20:19 UTC by BoDonkey

## Summary

*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*
This PR updates the cache and login modules. It was needed to allow for the cache-redis extension to function. Before this PR the number of login attempts was cleared by deleting the cached value from the MongoDB directly. As the cache-redis extension doesn't use MongoDB for caching, this led to an error. A new `delete` function was added to the cache module and the login module `clearLoginAttempts` method was altered to this new method. Closes PRO-5297.

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly
1. Spin-up a project
2. Confirm that login proceeds without error.
## What kind of change does this PR introduce?
*(Check at least one)*

- [X] Bug fix
- [X] New feature
- [X] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2023-12-19 20:36 UTC, boutell requested changes

2023-12-19 20:36 UTC, boutell commented on modules/@apostrophecms/cache/index.js
> +      async delete(username, namespace) {
Be consistent, namespace first

2023-12-20 11:14 UTC, BoDonkey commented on modules/@apostrophecms/cache/index.js
> +      async delete(username, namespace) {
Fixed

2023-12-20 15:38 UTC, boutell requested changes

2023-12-20 15:38 UTC, boutell commented on modules/@apostrophecms/login/index.js
> +      async clearLoginAttempts (namespace = loginAttemptsNamespace, username) {
Defaults for the first argument don't work if there is a second argument, which is required here

Also, tests are failing

2023-12-20 15:39 UTC, boutell commented on modules/@apostrophecms/login/index.js
> +      async clearLoginAttempts (namespace = loginAttemptsNamespace, username) {
I'm wrong about defaults not being supported for first arguments of several, if you pass undefined they are used

2023-12-20 21:22 UTC, boutell approved these changes

2023-12-21 10:23 UTC, merged