Widget editor: adds tabs
apostrophecms/apostrophe pull request #4514
Opened 2024-04-23 17:00 UTC by falkodev

https://linear.app/apostrophecms/issue/PRO-5134/widget-modals-that-support-schema-tabsgroups

2024-04-26 14:37 UTC, boutell requested changes
Generally great, need to fix that prop mutation though.

2024-04-26 14:37 UTC, boutell commented on modules/@apostrophecms/modal/ui/apos/components/AposModalTabs.vue
> +  <div class="apos-modal-tabs" :class="{ 'apos-modal-tabs--horizontal': orientation === 'horizontal' }">
let's gooooo very nice

2024-04-30 18:05 UTC, boutell submitted a review, later dismissed
Approved with my shallow clone fix (assigning to a variable doesn't copy the object).

2024-04-30 19:20 UTC, BoDonkey approved these changes

2024-04-30 19:20 UTC, merged