trigger validation only if we have currentId
apostrophecms/apostrophe pull request #4571
Opened 2024-06-08 12:19 UTC by haroun

## Summary

Fix error with array in vue production build

For future us, please also check https://github.com/apostrophecms/apostrophe/pull/4569

## What are the specific steps to test this change?

To enable the vue dev tools in production

```javascript
const apps = Array.from(document.querySelectorAll('*')).filter((e) => e.__vue_app__).map(e => e.__vue_app__)
const version = apps.at(0).version
const devtools = window.__VUE_DEVTOOLS_GLOBAL_HOOK__
devtools.enabled = true
apps.forEach(app => devtools.emit('app:init', app, version, {}))
```
1. `NODE_ENV=production npm run build && NODE_ENV=production node app.js`
2. Test with starting from an empty array and try to add an item
3. Test with an existing array and trigger a validation error, fix the validation error and then try to delete the item

## What kind of change does this PR introduce?
*(Check at least one)*

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2024-06-08 13:51 UTC, boutell approved these changes
Thank you

2024-06-11 10:18 UTC, ValJed requested changes

2024-06-11 10:18 UTC, ValJed commented on modules/@apostrophecms/schema/ui/apos/logic/AposArrayEditor.js
> +      this.evaluateConditions();
could be in a method `setCurrentDoc`.

2024-06-11 10:18 UTC, ValJed commented on modules/@apostrophecms/schema/ui/apos/logic/AposSchema.js
> +              data: this.modelValue[item.name] || {}
Are we  sure data is always supposed to be an object here?
Should be `this.modelValue.data[item.name]`. Looks like it's not used we should verify and create a ticket if needed.

2024-06-11 12:54 UTC, ValJed approved these changes

2024-06-11 12:54 UTC, ValJed commented on modules/@apostrophecms/schema/ui/apos/logic/AposArrayEditor.js
> +      this.triggerValidation = false;
I would have kept this line out but detail.

2024-06-11 12:55 UTC, merged