PRO-6050 fix all deprecation warnings that can reasonably be fixed at this time without bc issues
apostrophecms/apostrophe pull request #4576
Opened 2024-06-12 14:37 UTC by boutell

With this change:

```
rm -rf node_modules
rm package-lock.json
npm install --omit=dev
```

... Yields only one deprecation warning about `querystring` not being ideal in new code, and it has been traced to AWS SDK v2 in uploadfs. Upgrading from that library, which is still supported with security and bug fixes, would cause bc breaks for anyone passing an AWS.Credentials object directly to uploadfs so it is not acceptable at least to do without more thought.

2024-06-12 14:38 UTC, boutell commented
The tests are going to fail until `uploadfs` 1.22.4 gets published later today.

2024-06-17 07:14 UTC, ValJed requested changes
LGTM, just some missed logs.
Do we have a PR to do it in other modules? I know we use `cuid` in a lot of places.
Also, might be a good idea to run cypress tests ?

2024-06-17 07:14 UTC, ValJed commented on test/pieces.js
> +    console.log(response.choices._articles[0].value);
Forgotten logs?

2024-06-28 13:08 UTC, boutell commented
Val is out, his concern was addressed, and the failing tests also fail in `main`, they are an unrelated problem that can't be reproduced locally 🤔 So I'm merging this.

2024-06-28 13:08 UTC, merged