allow "shortcut: false" option to disable a shortcut
apostrophecms/apostrophe pull request #4584
Opened 2024-06-14 08:39 UTC by haroun

## Summary

Allow to disable a shortcut by setting the option `shortcut: false`

## What are the specific steps to test this change?

1. `npm test` must be green

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [ ] Related documentation has been updated
- [x] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2024-06-14 13:33 UTC, boutell approved these changes

2024-06-14 13:33 UTC, boutell approved these changes

2024-06-17 16:24 UTC, haroun commented
Fixed conflict in CHANGELOG.md

2024-06-17 16:50 UTC, boutell requested changes
4.4.3 just came out so the changelog will need one more round of attention. Hopefully no more hotfixes this week :laughing:

2024-06-18 13:56 UTC, boutell submitted a review, later dismissed

2024-06-26 09:50 UTC, ValJed approved these changes

2024-06-26 10:08 UTC, merged