Fix media update
apostrophecms/apostrophe pull request #4600
Opened 2024-06-25 12:58 UTC by ValJed

## Summary

*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2024-06-25 13:44 UTC, boutell submitted a review, later dismissed

2024-06-26 05:53 UTC, ValJed commented on modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue
> +        this.checkedDocs.splice(checkedDocsIndex, 1);
I need to do it for checkedDocs too since the watcher on `checked` is not triggered.
I still keep it this way since it's way faster than a filter.

2024-06-26 07:34 UTC, haroun requested changes

2024-06-26 07:34 UTC, haroun commented on modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue
> +        this.archiveDoc(doc);
these method names are confusing

2024-06-26 07:50 UTC, merged