improved admin tabbing
apostrophecms/apostrophe pull request #4658
Opened 2024-07-24 20:27 UTC by stuartromanek

## Summary
- increased focus visibility for admin bar piece manager buttons
- focus state for ‘subtle’ buttons (round + button in admin bar)
- improved accessibility / tab-ability in the locale switcher
- improved focus states for widget breadcrumbs
- context menus can be closed with `esc` .. focus returned to their parent trigger when closed
- All hidden area UI (area UI in its unhovered / unfocused state) now properly excludes itself from `tabindex` until hovered/focused (this was eating **a lot** of invisible focus tabbing)
- widget control UI reorganized for more intuitive tabbing order
- widget control UI focus state style improvements
- various accessibility tag updates

https://github.com/user-attachments/assets/6d9a3fef-a46c-4c08-ad0f-73a4d3553d3b

2024-07-31 10:30 UTC, ETLaurent submitted a review, later dismissed

2024-07-31 10:30 UTC, ETLaurent commented on modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
> +              :disable-focus="!(isHovered || isFocused)"
could we use `:tabbable="isHovered || isFocused"` here to be consistent?

2024-07-31 15:16 UTC, ETLaurent submitted a review, later dismissed

2024-08-01 10:58 UTC, ETLaurent requested changes

2024-08-01 10:58 UTC, ETLaurent commented on CHANGELOG.md
> +
duplicated `### Adds`

2024-08-01 11:18 UTC, ETLaurent commented
<img width="456" alt="image" src="https://github.com/user-attachments/assets/60574d1e-24cc-4dd1-897b-1fb8400fe26d">

focus on "image adjustement" and "close" icons seems broken, icons just shift a bit (no outline and nothing happens when pressing enter or space)

2024-08-01 14:35 UTC, ETLaurent approved these changes
Re-approving because I don't want to block the merge while I'm away.
The changelog just needs some format fixing

2024-08-01 20:12 UTC, BoDonkey approved these changes

2024-08-01 20:16 UTC, BoDonkey approved these changes

2024-08-01 20:16 UTC, merged