Pro 6660: modules order
apostrophecms/apostrophe pull request #4745
Opened 2024-10-05 14:43 UTC by myovchev

## Summary

 Modules can now have a `before: "module-name"` property in their configuration to run (initialization) before another module. That works only for target modules that are initializable. 

## What are the specific steps to test this change?

```js
// my-module/index.js
module.exports = {
  // will be initialized before the core image piece
  before: '@apostrophecms/image'
}
```

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [ ] Related documentation has been updated
- [x] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2024-10-07 12:44 UTC, boutell requested changes

2024-10-07 12:44 UTC, boutell commented on CHANGELOG.md
> +* Modules can now have a `before: "module-name"` property in their configuration to run (initialization) before another module. That works only for target modules that are initializable.
"Not initializable" means an "abstract base class" module, right? So the concept isn't relevant for them and it's OK to skip the warning I think.

2024-10-07 12:44 UTC, boutell commented on index.js
> +        console.warn(`Module "${name}" has a 'before' property that references itself. Skipping.`);
Throw an error, stop the show. This is a new feature and we get to insist on good behavior.

2024-10-07 12:44 UTC, boutell commented on index.js
> +        console.warn(`Module "${name}" has a 'before' property that references a non-existent module: "${before}". Skipping.`);
Throw an error, stop the show. This is a new feature and we get to insist on good behavior.

2024-10-08 14:19 UTC, boutell commented on index.js
> +        throw new Error(`Module "${name}" has a 'before' property that references itself. Skipping.`);
We're stopping, not skipping (:

2024-10-08 14:21 UTC, myovchev commented on index.js
> +        throw new Error(`Module "${name}" has a 'before' property that references itself. Skipping.`);
lol true :)

2024-10-08 15:48 UTC, boutell approved these changes

2024-10-08 17:14 UTC, merged