Breakpoint clear
apostrophecms/apostrophe pull request #4769
Opened 2024-10-16 15:44 UTC by stuartromanek

## Summary

- Adds a Clear Breakpoint button when breakpoint prev is activated
- Moves Breakpoint controls to the right side of the context bar

## What are the specific steps to test this change?

https://github.com/user-attachments/assets/a79fcb17-bf7f-4adb-9aff-f163a9166816

1. Activate a breakpoint
2. See the X button appear
3. click it and be returned to full preview

**⚠️ NOTE**
The intended responsive effect of the breakpoint preview UI is that the shortcuts container will disappear at small screen sizes. But, due to an issue with the way the breakpoint preview webpack media query loader currently works, ALL media queries (including apos admin styles) get scoped to the breakpoint preview mode and therefore the shortcuts container disappears _whenever_ breakpoint preview is activated. This is _not_ the intended effect, but as other admin elements are already affected by this, this PR does not try to address it.

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2024-10-16 17:25 UTC, boutell commented
ooo nice

2024-10-17 15:31 UTC, ValJed requested changes
Looks good, just a comment to remove.
Might worth running cypress tests before to merge.

2024-10-17 15:31 UTC, ValJed commented on modules/@apostrophecms/ui/ui/apos/scss/mixins/_theme_mixins.scss
>  $spacing-three-quarters: math.div($spacing-base, 4) * 3;
[Detail]
Could reuse `$spacing-one-quarter` in this line.

2024-10-17 15:51 UTC, stuartromanek commented on modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue
> +      /> -->
removed

2024-10-17 15:54 UTC, stuartromanek commented
Tests running here https://github.com/apostrophecms/testbed/actions/runs/11388565860

2024-10-17 20:17 UTC, stuartromanek commented
> Tests running here https://github.com/apostrophecms/testbed/actions/runs/11388565860

@ValJed tests for `import-export` are failing but they are failing the same way they are in `[main](https://github.com/apostrophecms/testbed/actions/runs/11375941148/job/31647661948)`

`¯\_(ツ)_/¯` ?

2024-10-22 13:30 UTC, merged