handle validate for choices
apostrophecms/apostrophe pull request #4793
Opened 2024-11-01 16:47 UTC by haroun

## Summary

*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2024-11-05 10:11 UTC, ValJed requested changes
Just would like @boutell opinion on a point.

2024-11-05 10:11 UTC, ValJed commented on modules/@apostrophecms/schema/index.js
> +            }
@boutell Would like your opinion on that:
In this file just before line `672` we add default value to hidden fields.
If this is necessary, I suppose that we should do the same thing when a parent is hidden?
WDYT?

2024-11-11 15:17 UTC, haroun commented
I've created https://linear.app/apostrophecms/issue/PRO-6799/set-default-values-for-invisible-fields

2024-11-11 16:26 UTC, ValJed submitted a review, later dismissed
LGTM

2024-11-11 16:30 UTC, boutell approved these changes

2024-11-13 08:54 UTC, ValJed approved these changes
LGTM, Might be improved in the future.

2024-11-13 10:35 UTC, merged