Pro 6843 context menu additional items
apostrophecms/apostrophe pull request #4819
Opened 2024-12-11 13:06 UTC by ValJed

[PRO-6843](https://linear.app/apostrophecms/issue/PRO-6843/as-a-user-i-want-to-be-able-to-move-palette-so-that-i-can-see-elements)

## Summary

I need to add in palette a new item in the context menu.
This item should not open any modal but just emit an event I could listen to know user clicked on it. So I cannot use `customOperations` here.

I just added the possibility to pass an array of extra items to a `AposDocContextMenu` component.
This one can be used to call an action like we already do, or to emit a simple event when closing to the parent, like I do with palette.

It allows me to do this in palette:
```javascript
          <AposDocContextMenu
            :doc="docFields.data"
            :show-edit="false"
            :additional-menu-items="[{
              label: 'aposPalette:resetPalettePosition',
              action: 'reset-position',
              emitEvent: true
            }]"
            @close="menuCloseHandler"
          />
```
If I pass `emitEvent` it will simply emit close with the `action` as parameter.

## What are the specific steps to test this change?
See above

## What kind of change does this PR introduce?

- [ ] Bug fix
- [X] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

2024-12-12 09:42 UTC, haroun submitted a review, later dismissed

2024-12-16 15:01 UTC, boutell requested changes
There is already a way to register additional context operations server side. The palette module can call:

```
self.apos.doc.addContextOperation({
  action: 'reset-palette-position',
  if: {
    type: self.__meta.type
  }  
});
```

This will make the operation available only for palette.

So there is no need to introduce a redundant way of registering custom context operations.

However I do think you may need a patch to allow them to trigger a bus event rather than opening a modal. This is the current logic that implements the "operation" property:

```
      const props = {
        moduleName: operation.moduleName || this.moduleName,
        // For backwards compatibility
        doc,
        ...docProps(doc),
        ...operation.props
      };
      await apos.modal.execute(operation.modal, props);
```

This will need an update to support emitting a bus event with an object containing the props as an alternative.

2024-12-16 15:11 UTC, boutell commented
(Excuse me, `self.__meta.name`, which is just a cute way of saying this module's name, you could also hardcode the string)

2024-12-16 16:36 UTC, boutell approved these changes
Approving for time but please fix changelog

2024-12-16 16:36 UTC, boutell commented on CHANGELOG.md
> +* Adds new prop `additionalMenuItems` to `AposDocContextMenu`. Allow to pass additional menu items that can trigger an action when clicked, or simply pass the action as the close event parameter.
Change

2024-12-16 17:56 UTC, boutell approved these changes

2024-12-17 08:50 UTC, merged